---
- name: Basic Hardware Monitoring Only
  ansible.builtin.apt:
    name:
      - smartmontools
      - htop
      - btop
    state: present
    update_cache: true
  become: true
  tags: ["monitoring"]

- name: Ensure Smartd is running
  ansible.builtin.systemd:
    name: smartmontools
    enabled: true
    state: started
  become: true
