# The task in charge of configuring the SQL server that K3s will use for its internal database.
# This one can only be called on the storage node(s).
# Currently, my setup only has a single storage node.
# Distributed SQL remains a mystery to me. I will not attempt.

---
- name: Install PostgreSQL
  ansible.builtin.apt:
    name:
      - postgresql
      - python3-psycopg2  # Required for Ansible to talk to Postgres
    state: present

- name: Ensure PostgreSQL is started and enabled
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true

- name: Create K3s database user
  community.postgresql.postgresql_user:
    name: "k3s_user"
    password: "{{ db_password }}"
    role_attr_flags: "CREATEDB"
  become: true
  become_user: postgres

- name: Create K3s database
  community.postgresql.postgresql_db:
    name: "k3s_db" # Name for the SQL database that K3s will use.
    owner: "k3s_user" # Name for the K3s SQL database that K3s will use.
  become: true
  become_user: postgres

- name: Allow remote connections in pg_hba.conf
  ansible.builtin.lineinfile:
    path: /etc/postgresql/16/main/pg_hba.conf  # Verify version number on Debian 13
    line: "host k3s_db k3s_user 0.0.0.0/0 md5"
  notify: Restart Postgres

# Makes sure the SQL Server can listen for external connections from other nodes in the cluster.
- name: Allow PostgreSQL to listen on all network interfaces
  ansible.builtin.lineinfile:
    path: /etc/postgresql/16/main/postgresql.conf
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '*'"
    validate: "/usr/lib/postgresql/16/bin/postgres --check -D /var/lib/postgresql/16/main -c config_file=%s"
  notify: Restart Postgres
