---
# The role in charge of configuring the storage environment that the K3s cluster will utilize.
# It is a combination of NFS, SQL Servers and iSCSI.

- name: Installing Necessary Packages
  ansible.builtin.apt:
    name:
      - nfs-kernel-server
      - targetcli-fb
    state: present
  tags: ["packages", "storage", "setup"]

- name: Create CSI User
  ansible.builtin.user:
    name: csi-admin
    state: present
  tags: ["csi", "storage", "setup"]

- name: Give csi-admin file permissions
  ansible.builtin.file:
    path: /mnt/tank/k3s/nfs
    owner: "csi-admin"
    mode: "0750"
    state: directory
  tags: ["csi", "storage", "setup"]

- name: Configure Sudoers for CSI Admin
  ansible.builtin.copy:
    dest: /etc/sudoers.d/csi-admin
    content: |
      csi-admin ALL=(ALL) NOPASSWD: /usr/sbin/zfs *, /usr/sbin/zpool *, /usr/bin/targetcli *, /usr/sbin/zvol *
    mode: "0440"
    validate: /usr/sbin/visudo -cf %s
  tags: ["csi", "storage", "setup"]
