haproxy_sni_backends:
  - name: headscale
    sni: headscale.yourdomain.com
    match: exact
    backend_host: 127.0.0.1
    backend_port: 8080
  - name: cluster
    sni: .yourdomain.com      # leading dot — suffix match catches *.yourdomain.com
    match: suffix
    backend_host: 10.10.0.0   # home gateway's WG address
    backend_port: 443


restic_b2_bucket: your-bucket-name
restic_timer: "02:30"
restic_keep_daily: 7
restic_keep_weekly: 4
restic_keep_monthly: 3

restic_backup_paths:
  - /opt/headscale/lib/db.sqlite.bak