---
- name: Initial Baseline for Debian 13
  hosts: metal
  become: true
  tasks:
    - name: Update and upgrade the system
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Install essential packages
      ansible.builtin.apt:
        name:
          - vim
          - ufw
          - htop
          - git
          - curl
          - docker
          - kubernetes
        state: present
