name: Release-Compiler
on:
  push:
    branches: ["main"]
    paths:
      - 'VERSION'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write 

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v6

      - id: get_version
        run: echo "V_NUM=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Move VERSION to LaTex root
        run: cp VERSION manual/src/VERSION

      - name: Compile LaTex to .pdf
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: manual/src
          root_file: main.tex

      - name: Create Release Draft
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ steps.get_version.outputs.V_NUM }}
          files: manual/src/main.pdf 
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}